export const spellListL1 = {
  spells: [
    "color-spray",
    "chaos-bolt",
    "expeditious-retreat",
    "hideous-laughter",
    "detect-poison-and-disease",
    "detect-evil-and-good",
    "find-familiar",
    "disguise-self",
    "false-life",
    "bane",
    "bless",
    "burning-hands",
    "alarm",
    "chromatic-orb",
    "feather-fall",
    "detect-magic",
    "cure-wounds",
    "faerie-fire",
    "identify",
    "charm-person",
  ],
  cantrips: [
    "acid-splash",
    "chill-touch",
    "dancing-lights",
    "mending",
    "shillelagh",
    "ray-of-frost",
    "vicious-mockery",
    "spare-the-dying",
  ],
};
